# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suitest < Formula
  desc "AI-powered testing agent CLI — provider-agnostic"
  homepage "https://github.com/mulhamna/suitest"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.2/suitest_darwin_amd64.tar.gz"
      sha256 "6cb8a39e0422942d06dcc62b3b24fc02e0b41cc67e5ed72f7143576595566afe"

      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.2/suitest_darwin_arm64.tar.gz"
      sha256 "b1c15d14ca0adc3b05924d589468f6b3de2c9a6b115ddda3e7ecae4451bbf639"

      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.2/suitest_linux_amd64.tar.gz"
      sha256 "5e29af25f920a6f7ea8cafdd2591e039b00049b25375a7fc88de69f21d28831f"
      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.2/suitest_linux_arm64.tar.gz"
      sha256 "d75b2be0539ebf6cec327acacf6e544a50015737e48d709aa3e4bd3644fa24af"
      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  test do
    system "#{bin}/suitest", "--version"
  end
end
