# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suitest < Formula
  desc "AI-powered testing agent CLI — provider-agnostic"
  homepage "https://github.com/mulhamna/suitest"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.1/suitest_darwin_amd64.tar.gz"
      sha256 "08eda1e60babe8b147c73cbc422fb2f44f9c99f8f6a9cd965873be2cb535d0ff"

      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.1/suitest_darwin_arm64.tar.gz"
      sha256 "8948bfd9c966cdc959a4cef1fa8195a59957ab673a2bd69c1559426054176aeb"

      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.1/suitest_linux_amd64.tar.gz"
      sha256 "685eaad8a18f860157a76b2dffbd745c4a20a2147a06de2a654e2cfd6a9a4c5c"
      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.1/suitest_linux_arm64.tar.gz"
      sha256 "a2802334e48b11c20c351e6c43008a4c0a0c51b3ccfbceb6afc54dd821355bd7"
      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  test do
    system "#{bin}/suitest", "--version"
  end
end
