# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Suitest < Formula
  desc "AI-powered testing agent CLI — provider-agnostic"
  homepage "https://github.com/mulhamna/suitest"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.3/suitest_darwin_amd64.tar.gz"
      sha256 "c291747597e9ac20b44a7a1666f8928dfbe60dbce1434eab68ebe2394e8a1fc2"

      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.3/suitest_darwin_arm64.tar.gz"
      sha256 "16e21d71949b9fe889faaac3d07e6dabf64fab4b3d8807c23331c942372d5b98"

      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.3/suitest_linux_amd64.tar.gz"
      sha256 "bfb2a15aa9f4b9076264992d9469a9332e1661c854522813fd62a6038b6984da"
      define_method(:install) do
        bin.install "suitest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mulhamna/suitest/releases/download/v1.0.3/suitest_linux_arm64.tar.gz"
      sha256 "d87a570a44b358aac1e7f89589b7c8d51d86862b12495303a8cec862506e0027"
      define_method(:install) do
        bin.install "suitest"
      end
    end
  end

  test do
    system "#{bin}/suitest", "--version"
  end
end
